config/routes.rb
Rails.application.routes.draw do
  get 'materials/new'
  get 'sessions/new'
  get 'users/new'
    root 'pages#index'
    get 'pages/help'
    get 'pages/aboutus'
    
#管理者へのメッセージに対応

    get 'inquiry' => 'inquiry#index'            #入力画面
    post 'inquiry/confirm' => 'inquiry#confirm' #確認画面
    post 'inquiry/thanks' => 'inquiry#thanks'   #通信完了画面

#ユーザー登録フォームに対応
  
    get 'signup', to: 'users#new'
    # resources :users, only: [:index, :show, :create, :edit, :update]

#サインインとセッション関連

    get '/login', to: 'sessions#new' 
    post '/login', to: 'sessions#create' 
    delete '/logout', to: 'sessions#destroy'
    
#素材投稿関連

  resources :users
  resources :materials

#『いいね』関連

    get 'favorites/index' 
    post '/favorites', to: 'favorites#create'
    post '/destroy', to: 'favorites#destroy'
    
#コメント機能関連

  resources :materials do 
    resources :comments
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :material
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord

    validates :name, :presence => {:message => 'お名前を入力してください。'}
    validates :message, :presence => {:message => '管理者へのメッセ‐ジを入力してください。'}

end

app/models/material.rb
class Material < ApplicationRecord
    validates :user_id, presence: true 
    validates :description, presence: true 
    validates :image, presence: true
    
    belongs_to :user
    
    mount_uploader :image, ImageUploader
    has_many :favorites
    has_many :favorite_users, through: :favorites, source: 'user'
    has_many :comments
    
end

app/models/user.rb
class User < ApplicationRecord
 
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password

  has_many :materials
  has_many :favorites
  has_many :favorite_materials, through: :favorites, source: 'material'
  
  has_many :comments 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
      @comment = Comment.new
      @material = Material.find_by(id: params[:material_id])
  end

  def create
      comment = Comment.new
      comment.user_id = current_user.id
      comment.material_id = params[:material_id]
      comment.content = params[:comment][:content]
  
      if comment.save
        redirect_to materials_path, success: 'コメント登録しました'
      else
        redirect_to materials_path, danger: 'コメント登録に失敗しました'
      end
      
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_materials = current_user.favorite_materials
  end

  def create
    
    if current_user.nil?
      redirect_to materials_path, danger: 'ログインしてください。'
    
    else
    
      favorite = Favorite.new
      favorite.user_id = current_user.id
      
      favorite.material_id = params[:material_id]

      if favorite.save
        redirect_to materials_path, success: 'お気に入りに登録しました'
      else
        redirect_to materials_path, danger: 'お気に入りに登録に失敗しました'
      end    
    end
  end
  
    # favorite = Favorite.new
    # favorite.user_id = current_user.id
    # favorite.material_id = params[:material_id]

    # if favorite.save
    #   redirect_to materials_path, success: 'お気に入りに登録しました'
    # else
    #   redirect_to materials_path, danger: 'お気に入りに登録に失敗しました'
    # end
  # end
  
  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, material_id: params[:material_id])
    favorite.destroy
    redirect_to materials_path, success: 'お気に入りを解除しました'
  end
  
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    #入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end
  
  def confirm
    #入力値のチェック
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      #OK, 確認画面を表示
      render :action => 'confirm'
    else
      #NG, 入力画面を再表示
      render :action=>'index'
    end
  end

  def thanks
    #メール送信
    @inquiry = Inquiry.new(inquiry_params)
    if params[:back]
      render :action => 'index'
    else
      InquiryMailer.received_email(@inquiry).deliver
      #完了画面を表示
      render :action => 'thanks'
    end
  end
  
  private 
  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  
  def index

  @materials = Material.order("updated_at desc").includes(:favorite_users)
#  @materials = Material.all.includes(:favorite_users)
#  @materials = Material.order("updated_at desc")

  end
  
  def new
    @material = Material.new
  end
  
  def create
    @material = current_user.materials.new(material_params)

    if @material.save
      redirect_to materials_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  private
  def material_params
    params.require(:material).permit(:image, :description)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def help
  end
  
  def aboutus
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    # user = User.find_by(email: params[:session][:email])
    # if user && user.authenticate(params[:session][:password])
    user =User.find_by(email_params)
    if user && user.authenticate(password_params[:password])
    
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end

  private
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
    
  def email_params
    params.require(:session).permit(:email)
  end

  def password_params
    params.require(:session).permit(:password)
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
  @user = User.new(user_params) #user_paramsはPOSTデータをチェックするメソッド
 
    if @user.save
      flash[:success] = '新しいユーザーを登録しました。'
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = 'ユーザーの登録に失敗しました。'
      render :new
    end
  end
  
  # def show
  #   @user = User.find(params[:id])
  # end
  
  private

  #ストロングパラメーター
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
#   def current_user
#     @current_user ||= User.find_by(id: session[:user_id])
#   end

#   def logged_in?
#     !current_user.nil?
#   end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="material-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">コメント入力フォーム</h1>
        <%= form_for [@material, @comment] do |f| %>
        
          <div class="form-group">
            <%= f.label :コメント %>
            <%= f.text_field :content,  class: 'form-control'  %>
          </div>

           <% if logged_in? %>
             <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
           <% end %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/inquiry/confirm.html.erb
<div class="col-md-offset-4 col-md-5 inquiry-container">
  <!--<h1 class="text-center text-black">入力内容確認</h1>-->

<!--<p></p>-->
<!--<div class="page-header">-->
<!--  <h1>入力内容確認</h1>-->
<!--</div>-->

<%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>

  <div>
    <h2>入力内容確認</h2>
    <div>
      <strong>お名前</strong>
      <p>
        <%= f.hidden_field :name %>
        <%= @inquiry.name %>
      </p>
    </div>
    <div>
      <strong>メールアドレス</strong>
      <p>
        <%= f.hidden_field :email %>
        <%= @inquiry.email %>
      </p>
    </div>
    <div>
      <strong>メッセージ</strong>
      <p>
        <%= f.hidden_field :message %>
        <%= simple_format(@inquiry.message) %>
      </p>
    </div>

  <!--<table class="table">-->
  <!--  <tr>-->
  <!--    <th>お名前</th>-->
  <!--    <td>-->
  <!--      <%= f.hidden_field :name %>-->
  <!--      <%= @inquiry.name %>-->
  <!--    </td>-->
  <!--  </tr>-->
  <!--  </tr>-->
  <!--    <th>メールアドレス</th>-->
  <!--    <td>-->
  <!--      <%= f.hidden_field :email %>-->
  <!--      <%= @inquiry.email %>-->
  <!--    </td>-->
  <!--  </tr>-->
  <!--  <tr>-->
  <!--    <th>メッセージ内容</th>-->
  <!--    <td>-->
  <!--      <%= f.hidden_field :message %>-->
  <!--      <%= simple_format(@inquiry.message) %>-->
  <!--    </td>-->
  <!--  </tr>-->
  <!--</table>-->
  <%= f.submit '戻る', name: 'back',:class => 'btn btn-primary' %>
  <%= f.submit '送信する',:class => 'btn btn-primary' %>
<% end %>

</div>

app/views/inquiry/index.html.erb
<!--<div class="users-new-wrapper">-->
  <!--<div class = "row">-->
  <!--  <div class="container">-->
  <div class="col-md-offset-4 col-md-5 inquiry-container">


  <%= simple_form_for(@inquiry, url: { action: :confirm }) do |f| %>
    <h2>サイト管理者へのメッセージ</h2>
    <%= f.input :name, label: "お名前（ニックネーム可）", placeholder: "20文字以内"  %>
    <%= f.input :email, label: "メールアドレス", placeholder: "30文字以内"  %>
    <%= f.input :message, as: :text, label: "メッセージ" %>
    <%= f.button :submit, "確認画面へ", :class => "btn-primary" %>
  <% end %>

  </div>
  <!--  </div>-->
  <!--</div>-->
<!--</div>-->

app/views/inquiry/thanks.html.erb
<div class="container aboutus-container">
<p><br/></p>

<H1>メッセージ受付完了</H1>

    <div class= "row">
    	<H3>ありがとうございました</H3>
    	<div class="col-md-3">
        <%= image_tag 'akihiro_face.JPG' %>
    	</div>
    	
      <div class="col-md-5">
		  <p>お問いあわせについては、数日以内にManga-Prospects管理者からお返事いたします。</p>
      <p>ご意見については、内容を検討し、Manga-Prospectsの改善に努めます。</p>
      <p>今後とも、Manga-Prospectsをよろしくお願いいたします。</p>
			</div>
    </div>

app/views/materials/index.html.erb
<div class="material-index-wrapper">
  <div class="container">
    <% @materials.each do |material| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="material-index-single">
            <h2 class="material-author">
              <%= material.user.name %>
            </h2>
            
            <%= image_tag material.image.url %>
            
            <% if !material.favorite_users.include?(current_user) %> 
              <%= link_to favorites_path(material_id: material.id), method: :post do %>
                 <%= image_tag 'icons/heart-black.png', class: 'material-index-icon' %>
              <% end %>
            <% else %>  
              <%= link_to destroy_path(material_id: material.id), method: :post do %>
                 <%= image_tag 'icons/heart-red.png', class: 'material-index-icon' %>
              <% end %>
            <% end %>
            
            <!-- 各マテリアルのお気に入りの数を表示 -->
            <%= material.favorite_users.count %>
            
            <!-- コメントマークからコメント入力画面へのリンク-->
            <%= link_to new_material_comment_path(material_id: material.id), method: :get do %>
              <%= image_tag 'icons/comment.png', class: 'material-index-icon' %>
            <% end %>
            
            <p class="material-text">
              <%= material.description %>
            </p>
            
            　<h5>コメント</h5>　　

             <% material.comments.each do |comment| %>
             <div style="clear:both">
               <%= comment.content %>
             </div>
             <% end %>
            
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/materials/new.html.erb
<div class="material-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">漫画素材投稿</h1>
        <%= form_for @material do |f| %>
          <div class="form-group">
            <%= f.label :素材ファイル %>
            <%= f.file_field :image%>
          </div>

          <div class="form-group">
            <%= f.label :説明 %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <% if logged_in? %>
            <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
          <% end %>
          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<!--<div class="users-new-wrapper">-->
<!--  <div class = "row">-->
<!--    <div class="container">-->
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-black">ユーザー登録</h1>

        <%= form_for(@user) do |f| %>
          <div class="form-group">
            <%= f.label :name, 'お名前（ニックネーム可）' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :email, 'メールアドレス[ユーザーIDとして使用]' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（もう１度ご入力ください）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        
        <%= f.submit '登録する', class: 'btn btn-primary btn-block' %>
        <% end %>

    </div>
<!--    </div>-->
<!--  </div>-->
<!--</div>-->

app/views/users/show.html.erb
<div class="users-new-wrapper">
  <div class = "row">
    <div class="container">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">ユーザー情報</h1>
        <div class="row">
          <aside class="col-md-4">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title"><%= @user.name %></h3>
              </div>
            </div>
          </aside>
        </div>
      </div>
    </div>
  </div>
</div>