config/routes.rb
Rails.application.routes.draw do
  get 'materials/new'
  get 'sessions/new'
  get 'users/new'
    root 'pages#index'
    get 'pages/help'
    get 'pages/aboutus'
    
#管理者へのメッセージに対応

    get 'inquiry' => 'inquiry#index'            #入力画面
    post 'inquiry/confirm' => 'inquiry#confirm' #確認画面
    post 'inquiry/thanks' => 'inquiry#thanks'   #通信完了画面

#ユーザー登録フォームに対応
  
    get 'signup', to: 'users#new'
    # resources :users, only: [:index, :show, :create, :edit, :update]

#サインインとセッション関連

    get '/login', to: 'sessions#new' 
    post '/login', to: 'sessions#create' 
    delete '/logout', to: 'sessions#destroy'
    
#素材投稿関連

  resources :users
  resources :materials

#『いいね』関連

    get 'favorites/index' 
    post '/favorites', to: 'favorites#create'
    post '/destroy', to: 'favorites#destroy'
    
#コメント機能関連

  resources :materials do 
    resources :comments
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :material
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord

    validates :name, :presence => {:message => 'お名前を入力してください。'}
    validates :message, :presence => {:message => '管理者へのメッセ‐ジを入力してください。'}

end

app/models/material.rb
class Material < ApplicationRecord
    validates :user_id, presence: true 
    validates :description, presence: true 
    validates :image, presence: true
    
    belongs_to :user
    
    mount_uploader :image, ImageUploader
    has_many :favorites
    has_many :favorite_users, through: :favorites, source: 'user'
    has_many :comments
    
end

app/models/user.rb
class User < ApplicationRecord
 
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password

  has_many :materials
  has_many :favorites
  has_many :favorite_materials, through: :favorites, source: 'material'
  
  has_many :comments 

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
      @comment = Comment.new
      @material = Material.find_by(id: params[:material_id])
  end

  def create
      comment = Comment.new
      comment.user_id = current_user.id
      comment.material_id = params[:material_id]
      comment.content = params[:comment][:content]
  
      if comment.save
        redirect_to materials_path, success: 'コメント登録しました'
      else
        redirect_to materials_path, danger: 'コメント登録に失敗しました'
      end
      
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_materials = current_user.favorite_materials
  end

  def create
    
    if current_user.nil?
      redirect_to materials_path, danger: 'ログインしてください。'
    
    else
    
      favorite = Favorite.new
      favorite.user_id = current_user.id
      
      favorite.material_id = params[:material_id]

      if favorite.save
        redirect_to materials_path, success: 'お気に入りに登録しました'
      else
        redirect_to materials_path, danger: 'お気に入りに登録に失敗しました'
      end    
    end
  end
  
    # favorite = Favorite.new
    # favorite.user_id = current_user.id
    # favorite.material_id = params[:material_id]

    # if favorite.save
    #   redirect_to materials_path, success: 'お気に入りに登録しました'
    # else
    #   redirect_to materials_path, danger: 'お気に入りに登録に失敗しました'
    # end
  # end
  
  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, material_id: params[:material_id])
    favorite.destroy
    redirect_to materials_path, success: 'お気に入りを解除しました'
  end
  
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    #入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end
  
  def confirm
    #入力値のチェック
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      #OK, 確認画面を表示
      render :action => 'confirm'
    else
      #NG, 入力画面を再表示
      render :action=>'index'
    end
  end

  def thanks
    #メール送信
    @inquiry = Inquiry.new(inquiry_params)
    if params[:back]
      render :action => 'index'
    else
      InquiryMailer.received_email(@inquiry).deliver
      #完了画面を表示
      render :action => 'thanks'
    end
  end
  
  private 
  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  
  def index

  @materials = Material.order("updated_at desc").includes(:favorite_users)
#  @materials = Material.all.includes(:favorite_users)
#  @materials = Material.order("updated_at desc")

  end
  
  def new
    @material = Material.new
  end
  
  def create
    @material = current_user.materials.new(material_params)

    if @material.save
      redirect_to materials_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  private
  def material_params
    params.require(:material).permit(:image, :description)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def help
  end
  
  def aboutus
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    # user = User.find_by(email: params[:session][:email])
    # if user && user.authenticate(params[:session][:password])
    user =User.find_by(email_params)
    if user && user.authenticate(password_params[:password])
    
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end

  private
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
    
  def email_params
    params.require(:session).permit(:email)
  end

  def password_params
    params.require(:session).permit(:password)
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
  @user = User.new(user_params) #user_paramsはPOSTデータをチェックするメソッド
 
    if @user.save
      flash[:success] = '新しいユーザーを登録しました。'
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = 'ユーザーの登録に失敗しました。'
      render :new
    end
  end
  
  # def show
  #   @user = User.find(params[:id])
  # end
  
  private

  #ストロングパラメーター
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
#   def current_user
#     @current_user ||= User.find_by(id: session[:user_id])
#   end

#   def logged_in?
#     !current_user.nil?
#   end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manga Prospects</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <meta name="" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    <!-- Navigation bar from here --!>
    <header>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                 aria-expanded="false">
                <button type="button" class="navbar-toggle collapsed">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar">&nbsp;</span>
                    <span class="icon-bar">&nbsp;</span>
                    <span class="icon-bar">&nbsp;</span>
                </button>
                <!--<a class="navbar-brand" href="/">Manga Prospects</a>-->
                <%= link_to 'Manga Prospects', root_path, class: "navbar-brand" %>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <!--<li><a href="#">このサイトについて</a></li>-->
                    <li class="nav-item">
                      <%= link_to "このサイトについて",pages_aboutus_path, class: "nav-link" %>
                    </li>
                    <% if ! logged_in? %>
                      <li>
                        <%= link_to "ユーザー登録",users_new_path, class: "nav-link" %>
                      </li>
                      <li class="nav-item">
                        <%= link_to "ログイン",login_path, class: "nav-link" %>
                      </li>
                    <% else %>
                      <li>
                        <%= link_to "ユーザー登録",root_path, class: "nav-link" %>
                      </li>
                      <li class="nav-item">
                        <%= link_to "ログイン",root_path, class: "nav-link" %>
                      </li>
                    <% end %>
                    <% if logged_in? %>
                      <li class="nav-item">
                        <%= link_to logout_path,method: :delete do%>ログアウト<% end %>
                      </li>
                    <% else %>
                      <li class="nav-item">
                        <%= link_to "ログアウト",root_path,　class: "nav-link" %>
                      </li>
                    <% end %>
                    <!--<li><a href="#">管理者へ連絡</a></li>-->
                    <li class="nav-item active">                    
                     <%= link_to "管理者へ連絡",inquiry_path, class: "nav-link active" %>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
  
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
  
    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
    
  </body>
</html>

app/views/pages/aboutus.html.erb
</br>
</br>

<div class="container aboutus-container">

<H1>このサイトについて</H1>

    <div class= "row">
    	<H3>サイト管理者紹介</H3>
    	<div class="col-md-3">
        <%= image_tag 'akihiro_face.JPG' %>
    	</div>
    	
      <div class="col-md-5">
			名前：Akihiro Senda</br></br>
			<p>鉄鋼メーカー勤務、外資系PCメーカー勤務を経て、フリーのITエンジニアとなる。ながらくSIerとしての業務を多くこなしてきたが、今後はWebエンジニアとしての業務も手掛けることができるようになるべく、奮戦中。</p>
			<p><%= link_to "ご意見、ご要望などのご連絡はこちらからどうぞ。", inquiry_path %></p>
			</div>
    </div>
    
    <hr size="300">
    
    <div class= "row"> 
      <H3>このサイトの使い方（開発途上です）</H3>
      <div class="col-md-8">
        
        <p>このサイトは、主に売り出し中の漫画家や漫画家志望者の向けに、ご自身が権利を持っている漫画素材を公開する場を提供するものです。</p>

<p>使い方は以下のとおりです。</p>


<p><b>【素材投稿までの流れ】</b></p>

<p>１）ユーザー登録をする (登録済みの場合は不要です)</p>
<p>Webサイト上部のナビゲーションバーで「ユーザー登録」ボタンをクリックして開く入力画面に、ニックネームなどの必要な項目を入力して、【登録する】ボタンをクリックしてください。</p>
<p></p>
<p>２）ログインする</p>
<p></p>
<p>　ナビゲーションバーで「ログイン」ボタンをクリックして、開く入力画面に、メールアドレスとパスワードを入力して、【ログインする】ボタンをクリックしてください。</p>
<p></p>
<p>３）漫画素材を投稿する</p>
<p>　ナビゲーションバーの左端にある[Manga Prospects]をクリックすると、サイトのトップページが表示されます。この画面に表示されている【漫画素材投稿】ボタンをクリックすると、入力画面が表示されます。</p>

<p>‐[ファイルを選択]ボタンをクリックすると、ファイル選択用のサブウィンドウが開くので、あなたが公開しようとしている素材のファイルを選択してください。</p>

<p>‐Description欄に、素材に対する説明を入力してください。著作権表示や、あなたのWebサイトのURLを記入していただいてもかまいません。</p>


<p>※ユーザーログインした状態でなければ、【投稿】ボタンが表示されないため、素材投稿することができません。</p>

<p>４）ログアウトする</p>
<p>ナビゲーションバーで「ログアウト」ボタンをクリックする。</p>

<p><b>【素材一覧表示】</b></p>

<p>　ナビゲーションバーの左端にある[Manga Prospects]をクリックすると、サイトのトップページが表示されます。この画面に表示されている【投稿素材一覧】ボタンをクリックすると、投稿された素材が一覧表示されます。</p>

<p><b>【管理者への連絡】</b></p>

<p>　ナビゲーションバーの右端にある[管理者へ連絡]をクリックすると、「サイト管理者へのメッセージ」画面に切り替わります。</p>
<p>　この画面に、ニックネーム、送信するメッセージ、もしよろしければあなたのメールアドレスを入力していただき、【確認】ボタンを押していただくと、入力内容確認画面に切り替わります。
よろしければ【送信】ボタンを押していただくと、サイト管理者 Akihiro Senda にメッセージが送信されます。</p>

<p>※このサイトはいまだ開発中です。今後の改善や機能追加に関するご意見をお待ちしております。</p>

      </div>
    </div>
  
    <hr size="300">  
    
    <div class= "row">
    	<H3>Manga Prospects とは</H3>
      <div class="col-md-8">
<p>私自身は漫画家を目指したことはありません。絵を描くのもヘタクソだし、大勢の人たちの注目を集めるようなストーリーづくりが自分にできるとも思っていません。</p>

<p>だけど、遅咲きともいえる年代の漫画家志望者や売り出し中の漫画家の方を応援したいという気持ちは強くあります。</p>

<p>２０代後半でこれから漫画家としての未来を開こうしていているあなた！</p>

<p>10代後半～20代前半の漫画家志望さんと同じことをしていてはダメです。
初作品で賞を受賞して、とんとん拍子に連載決定!? なんてそんな人はきっとごくまれですよね... ！?
</p>

<p>デビューできたとしても、連載までたどり着けるには、きっと何年もかかるはず。</p>
<p>あなたはもう２0代後半。</p>

<p>遠回りしているヒマはありませんよ。
プロの漫画家になるということは、売れる作品をつくるということのはず。</p>

<p>夢を追うのではなく、現実を直視して売れる作品をつくるにはどうすればいいのか一緒に考えていきたい。</p>

<p>そのための場を提供したい。</p>

<p>そんな思いを込めて、私は Manga-Prorpsectsをつくっています。</p>

<p>漫画業界では全くの素人の私が、漫画家として成功したいあなたをWebの力を借りて応援する。</p>

<p>そのための試行の場がこの Manga-Prorpsects です。</p>
      </div>
    </div> 

    <hr size="300">
    
    <div class= "row"> 
      <H3>利用規約（立案中）</H3>
      <div class="col-md-11">
				<p>Manga-Prospectsでは、まず、漫画素材の共有、すなわち、素材投稿/ダウンロードサービスの提供から応援を始めます。</p>
				
				<p>今のところ、次のような主旨の利用規約を想定しています。</p>
				
				
<p>- 投稿された素材の著作権は　Manga-prospects に帰属しない。素材の投稿者の持つ権利が保持される。 </p>
<p>- 投稿された素材の販売権を、Manga-Prospectsは制限しない。投稿者は正当な権利に基づき、素材を販売することができる。 </p>
<p>- 画像投稿者は、自身が持つ正当な権利※に基づき、素材の投稿・配布・販売を行う。</p>
<p>- 素材のダウンロード者は、各素材に定められた権利※の範囲内で、その素材を利用することができる。</p>
<p></p>
<p>【禁止行為】</p>
<p></p>
下記のような素材の投稿を禁止します。
<p></p>
<p>- 犯罪に関与するもの。</p>
<p>- 法令や公序良俗に反するもの。</p>
<p>- 性器のあからさまな描写、異常な性行為の描写が含まれているもの。</p>
<p>- その他、Manga-prospects の運営目的にそぐわないもの。</p>
<p></p>
<p>※漫画界での素材共有の権利形態については、サイト管理人自身よくわかっていないというのが実態です。</p>
<p>　有識者の皆様からのアドバイスをいただけると幸いです。</p>
<p>※性的な描写が入った素材を禁止するということではありません。</p>
      </div>
		</div>

</div>

app/views/pages/help.html.erb
<h1>ヘルプページです</h1>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
 
    <h3 class="text-black">We are fellow !</h2>
    <h3 class="text-black">Manga-Prospects is a service with which we can share your Manga materials.</h2>

  <div class="container top-hero-container">

    <div class= "row">
      
      <div class="col-md-offset-3 col-xs-3">
        <%= link_to '漫画素材投稿', new_material_path, class: 'btn btn-info btn-lg' %>
        <!--<%= link_to '漫画素材投稿', new_material_path, class: 'btn btn-block btn-black' %>-->
      </div>
      
      <div class="col-xs-3">
        <%= link_to '投稿素材一覧', materials_path, class: 'btn btn-info btn-lg' %>
        <!--<%= link_to '投稿素材一覧', materials_path, class: 'btn btn-block btn-black' %>-->
      </div>
      
    </div>

  </div>
</div>